name: Terraform Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  COUNTRY: us
  ENVIRONMENT: stage

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # 修改为你实际使用的版本

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make unzip

      - name: Terraform Init
        run: |
          export COUNTRY=${{ env.COUNTRY }}
          export ENVIRONMENT=${{ env.ENVIRONMENT }}
          make init

      - name: Terraform Plan
        run: |
          export COUNTRY=${{ env.COUNTRY }}
          export ENVIRONMENT=${{ env.ENVIRONMENT }}
          make plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          export COUNTRY=${{ env.COUNTRY }}
          export ENVIRONMENT=${{ env.ENVIRONMENT }}
          make apply APPROVE=true