name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  env:
  AWS_REGION: us-east-2
  AWS_DEFAULT_REGION: us-east-2
  AWS_PROFILE: ""
  AWS_SDK_LOAD_CONFIG: "false"           # ✅ 核心：禁用 profile 加载
  COUNTRY: us
  ENVIRONMENT: stage

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make unzip

      - name: Terraform Init
        run: make init AWS_PROFILE=${{ env.AWS_PROFILE }} COUNTRY=${{ env.COUNTRY }} ENVIRONMENT=${{ env.ENVIRONMENT }}

      - name: Terraform Plan
        run: make plan AWS_PROFILE=${{ env.AWS_PROFILE }} COUNTRY=${{ env.COUNTRY }} ENVIRONMENT=${{ env.ENVIRONMENT }}

      - name: Terraform Apply (only on main branch)
        if: github.ref == 'refs/heads/main'
        run: make apply AWS_PROFILE=${{ env.AWS_PROFILE }} COUNTRY=${{ env.COUNTRY }} ENVIRONMENT=${{ env.ENVIRONMENT }} APPROVE=true