name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  AWS_DEFAULT_REGION: us-east-2
  COUNTRY: us
  ENVIRONMENT: stage

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make unzip

      - name: Terraform Init
        run: make init AWS_PROFILE=ipe-rootdeployer COUNTRY=${{ env.COUNTRY }} ENVIRONMENT=${{ env.ENVIRONMENT }}

      - name: Terraform Plan
        run: make plan AWS_PROFILE=ipe-rootdeployer COUNTRY=${{ env.COUNTRY }} ENVIRONMENT=${{ env.ENVIRONMENT }}

      - name: Terraform Apply (only on main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: make apply AWS_PROFILE=ipe-rootdeployer COUNTRY=${{ env.COUNTRY }} ENVIRONMENT=${{ env.ENVIRONMENT }}